---
- name: Check if prometheus is installed
  ansible.builtin.stat:
    path: "/usr/local/bin/prometheus"
  register: prometheus_binary
  tags:
    - prometheus.install

- include: install.yml
  when: not prometheus_binary.stat.exists or prometheus_force_install
  tags:
    - prometheus.install

- include: configure.yml
  tags:
    - prometheus.configure

- name: Ensure prometheus service is started and enabled
  ansible.builtin.systemd:
    daemon_reload: true
    name: prometheus
    state: started
    enabled: true
